### ISSUE TITLE
Unknown column 'j1.elements' in 'field list'

### ISSUE THREAD

**Issue by barrystaes** [terminal42/contao-ce-access#6]
I just found that when installing ce-access v2.0.2 on Contao v3.5.24 it went into maintainence mode by itself (red indication in backend), and i encountered this error on the frontpage:

```
Fatal error: Uncaught exception Exception with message Query error: Unknown column 'j1.elements' in 'field list' (SELECT tl_article.*, j1.id AS author__id, j1.tstamp AS author__tstamp, j1.username AS author__username, j1.name AS author__name, j1.email AS author__email, j1.language AS author__language, j1.backendTheme AS author__backendTheme, j1.uploader AS author__uploader, j1.showHelp AS author__showHelp, j1.thumbnails AS author__thumbnails, j1.useRTE AS author__useRTE, j1.useCE AS author__useCE, j1.password AS author__password, j1.pwChange AS author__pwChange, j1.admin AS author__admin, j1.groups AS author__groups, j1.inherit AS author__inherit, j1.modules AS author__modules, j1.themes AS author__themes, j1.pagemounts AS author__pagemounts, j1.alpty AS author__alpty, j1.filemounts AS author__filemounts, j1.fop AS author__fop, j1.forms AS author__forms, j1.formp AS author__formp, j1.disable AS author__disable, j1.start AS author__start, j1.stop AS author__stop, j1.session AS author__session, j1.dateAdded AS author__dateAdded, j1.lastLogin AS author__lastLogin, j1.currentLogin AS author__currentLogin, j1.loginCount AS author__loginCount, j1.locked AS author__locked, j1.elements AS author__elements, j1.faqs AS author__faqs, j1.faqp AS author__faqp, j1.news AS author__news, j1.newp AS author__newp, j1.newsfeeds AS author__newsfeeds, j1.newsfeedp AS author__newsfeedp FROM tl_article LEFT JOIN tl_user j1 ON tl_article.author=j1.id WHERE tl_article.pid='3' AND tl_article.inColumn='header' AND (tl_article.start='' OR tl_article.start<='1489018800') AND (tl_article.stop='' OR tl_article.stop>'1489018860') AND tl_article.published='1' ORDER BY tl_article.sorting) thrown in system/modules/core/library/Contao/Database/Statement.php on line 295

#0 system/modules/core/library/Contao/Database/Statement.php(264): Contao\Database\Statement->query()
#1 system/modules/core/library/Contao/Model.php(1089): Contao\Database\Statement->execute(Array)
#2 system/modules/core/library/Contao/Model.php(965): Contao\Model::find(Array)
#3 system/modules/core/models/ArticleModel.php(232): Contao\Model::findBy(Array, Array, Array)
#4 system/modules/core/library/Contao/Controller.php(242): Contao\ArticleModel::findPublishedByPidAndColumn('3', 'header')
#5 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'header')
#6 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#7 index.php(20): Contao\FrontendIndex->run()
#8 {main}
```

Removing the extension fixed this.

**Comment by aschempp** [comment]
Looks like you did not update the database after installing the extension.

**Comment by barrystaes** [comment]
You are right, works fine now.

(Contao went into maintainence mode though, didnt expect that)
